<?php
$page_title = 'Oferta Académica | INCB';
$page_desc  = 'Conoce en detalle los bachilleratos que ofrece el Instituto Nacional de Ciudad Barrios (INCB): duración, plan de estudios, perfil de egreso y requisitos.';

$bachilleratos = [
    'general' => ['titulo' => 'Bachillerato General', 'badge' => 'Duración: 2 años', 'duracion' => '2 años', 'icono' => 'bi-mortarboard-fill', 'descripcion' => 'Formación integral con énfasis humanístico y científico, pensada para quienes buscan una base académica sólida antes de continuar estudios universitarios en cualquier área.', 'plan' => ['Matemática, Física y Ciencias Naturales', 'Lenguaje y Literatura', 'Ciencias Sociales y Cívica', 'Inglés técnico', 'Orientación para la Vida'], 'perfil' => 'Egresas con las bases necesarias para continuar cualquier carrera universitaria, con pensamiento crítico, hábitos de estudio y valores ciudadanos consolidados.'],
    'software' => ['titulo' => 'Bachillerato en Desarrollo de Software', 'badge' => 'Duración: 3 años', 'duracion' => '3 años', 'icono' => 'bi-code-slash', 'distintivo' => 'Alta demanda', 'descripcion' => 'Formación técnica en lógica de programación, bases de datos y desarrollo de sistemas, orientada a que el estudiante egrese con habilidades reales para trabajar o emprender en tecnología.', 'plan' => ['Lógica de programación y algoritmos', 'Programación web (HTML, CSS, PHP, JS)', 'Bases de datos (MySQL)', 'Redes y mantenimiento de equipo', 'Proyecto final / pasantía técnica'], 'perfil' => 'Egresas con la capacidad de diseñar, programar y dar mantenimiento a sistemas y páginas web básicas, con bases sólidas para continuar estudios en Ingeniería o Licenciatura en Computación.'],
    'contable' => ['titulo' => 'Bachillerato Administrativo Contable', 'badge' => 'Duración: 3 años', 'duracion' => '3 años', 'icono' => 'bi-calculator-fill', 'descripcion' => 'Prepara al estudiante en gestión financiera, contabilidad y administración de empresas, con una fuerte orientación práctica hacia el mundo laboral y el emprendimiento.', 'plan' => ['Contabilidad general y de costos', 'Legislación tributaria y mercantil', 'Administración de empresas', 'Ofimática (Excel, Word aplicado a negocios)', 'Prácticas administrativas'], 'perfil' => 'Egresas con capacidad para llevar la contabilidad de una pequeña empresa, apoyar áreas administrativas y financieras, o continuar estudios en Contaduría, Administración de Empresas o carreras afines.'],
    'distancia' => ['titulo' => 'Bachillerato a Distancia', 'badge' => 'Modalidad flexible', 'duracion' => 'Modalidad flexible', 'icono' => 'bi-laptop', 'descripcion' => 'Pensado para estudiantes que trabajan, viven lejos o necesitan compatibilizar sus estudios con otras responsabilidades. Combina sesiones virtuales con encuentros presenciales periódicos.', 'plan_titulo' => 'Cómo funciona', 'plan' => ['Clases y materiales a través del aula virtual', 'Encuentros presenciales de tutoría y evaluación', 'Acompañamiento docente durante todo el proceso', 'Mismo plan de estudios que la modalidad presencial'], 'perfil_titulo' => 'Ideal para', 'perfil' => 'Jóvenes y adultos que necesitan retomar o continuar su bachillerato con horarios flexibles, sin sacrificar la calidad ni el acompañamiento académico.'],
];

$tab_activa = $_GET['tab'] ?? 'general';
$tab_activa = array_key_exists($tab_activa, $bachilleratos) ? $tab_activa : 'general';
require __DIR__ . '/../includes/header.php';
?>
<style>
  .oa-eyebrow { color: var(--incb-dorado, #b3922a); font-size: .78rem; font-weight: 600; letter-spacing: 2px; text-transform: uppercase; }
  .oa-hero-rule { width: 64px; height: 3px; background: var(--incb-dorado, #b3922a); margin: 1rem auto 0; }
  .programa-icon { width: 52px; height: 52px; display: flex; align-items: center; justify-content: center; border-radius: .35rem; background: #fff; border: 1px solid var(--incb-azul); color: var(--incb-azul); font-size: 1.4rem; flex-shrink: 0; }
  .oa-pills .nav-link i { display: inline-block; width: 25px; text-align: center; }
  .programa-detalle { scroll-margin-top: 90px; border-radius: .375rem !important; }
  .lista-check li { display: flex; align-items: flex-start; gap: .6rem; margin-bottom: .55rem; color: #444; }
  .lista-check i { color: var(--incb-azul); margin-top: 3px; flex-shrink: 0; }
  .oa-panel-header { border-bottom: 1px solid #eef0f3; padding-bottom: 1rem; margin-bottom: 1.25rem; }
  .oa-pills .nav-link { color: var(--incb-azul); text-align: left; font-weight: 600; }
  .oa-pills .nav-link:not(.active):hover { background-color: var(--bs-light); color: var(--incb-azul-oscuro); }
  .oa-pills .nav-link.active { background: var(--incb-azul-oscuro); color: #fff; }
</style>
<section class="py-5" style="background: var(--incb-azul-oscuro); color: #fff;"><div class="container text-center"><div class="oa-eyebrow">Instituto Nacional de Ciudad Barrios</div><h1 class="fw-brand fw-bold display-6 mt-1">Oferta Académica</h1><p class="mb-0" style="color: rgba(255,255,255,.8);">Todo lo que necesitas saber antes de inscribirte para el ciclo 2026</p><div class="oa-hero-rule"></div></div></section>
<div class="container py-5"><div class="row g-4 g-lg-5"><div class="col-lg-3 d-none d-lg-block"><div class="sticky-top" style="top: 90px;"><div class="border rounded-3 bg-white p-2"><div class="text-uppercase small fw-bold text-secondary px-2 py-2" style="letter-spacing: 1px;">Bachilleratos</div><nav id="pills-programas" class="nav nav-pills flex-column gap-1 oa-pills" aria-label="Seleccionar bachillerato" role="tablist">
<?php foreach ($bachilleratos as $clave => $bachillerato): $tab_id = 'tab-' . $clave; $es_activa = $clave === $tab_activa; ?><button class="nav-link <?= $es_activa ? 'active' : ''; ?>" id="<?= $tab_id; ?>-tab" data-bs-toggle="pill" data-bs-target="#<?= $tab_id; ?>" type="button" role="tab" aria-controls="<?= $tab_id; ?>" aria-selected="<?= $es_activa ? 'true' : 'false'; ?>"><i class="bi <?= $bachillerato['icono']; ?> me-2"></i><?= htmlspecialchars($bachillerato['titulo']); ?></button><?php endforeach; ?></nav></div><a href="<?= $base_url; ?>inscripcion.php" class="btn btn-outline-dark w-100 mt-3" style="border-radius:.3rem; font-weight:600;"><i class="bi bi-send-fill me-2"></i>Inscripción</a></div></div>
<div class="col-lg-9"><div id="contenido-especialidad" class="tab-content">
<?php foreach ($bachilleratos as $clave => $bachillerato): $tab_id = 'tab-' . $clave; $es_activa = $clave === $tab_activa; ?><article id="<?= $tab_id; ?>" class="tab-pane fade <?= $es_activa ? 'show active' : ''; ?> programa-detalle p-4 p-md-5 border bg-white shadow-sm" role="tabpanel" aria-labelledby="<?= $tab_id; ?>-tab" tabindex="0"><div class="d-flex align-items-center gap-3 oa-panel-header"><div class="programa-icon"><i class="bi <?= $bachillerato['icono']; ?>"></i></div><div><h2 class="h4 fw-bold mb-1"><?= htmlspecialchars($bachillerato['titulo']); ?></h2><span class="badge bg-primary-subtle text-primary"><?= htmlspecialchars($bachillerato['badge']); ?></span><?php if (!empty($bachillerato['distintivo'])): ?><span class="badge ms-1" style="border-radius:.25rem; background: var(--incb-dorado); color:#fff;"><?= htmlspecialchars($bachillerato['distintivo']); ?></span><?php endif; ?></div></div><p class="text-muted"><?= htmlspecialchars($bachillerato['descripcion']); ?></p><hr class="text-muted opacity-25 my-4"><div class="row g-4 mt-2"><div class="col-md-6"><h3 class="h6 fw-bold text-uppercase" style="color: var(--incb-azul);"><?= htmlspecialchars($bachillerato['plan_titulo'] ?? 'Plan de estudios incluye'); ?></h3><ul class="list-unstyled lista-check"><?php foreach ($bachillerato['plan'] as $materia): ?><li><i class="bi bi-check-circle-fill"></i><?= htmlspecialchars($materia); ?></li><?php endforeach; ?></ul></div><div class="col-md-6"><h3 class="h6 fw-bold text-uppercase" style="color: var(--incb-azul);"><?= htmlspecialchars($bachillerato['perfil_titulo'] ?? 'Perfil de egreso'); ?></h3><p class="text-muted small mb-0 lh-lg"><?= htmlspecialchars($bachillerato['perfil']); ?></p></div></div><a href="<?= $base_url; ?>inscripcion.php" class="btn btn-outline-warning mt-4"><i class="bi bi-send-fill me-2"></i>Inscribirme a esta especialidad</a></article><?php endforeach; ?></div>
<div id="requisitos" class="programa-detalle p-4 p-md-5 mt-4 border" style="background: var(--incb-azul-claro); border-color: rgba(0,0,0,.05) !important;"><h3 class="h5 fw-bold mb-3"><i class="bi bi-clipboard-check me-2" style="color: var(--incb-azul);"></i>Requisitos de ingreso (todos los bachilleratos)</h3><ul class="list-unstyled lista-check mb-4"><li><i class="bi bi-check-circle-fill"></i>Partida de nacimiento original y copia</li><li><i class="bi bi-check-circle-fill"></i>Constancia de notas o título de noveno grado</li><li><i class="bi bi-check-circle-fill"></i>NIE (Número de Identificación Estudiantil) válido</li><li><i class="bi bi-check-circle-fill"></i>2 fotografías tamaño carnet</li></ul><a href="<?= $base_url; ?>index.php#contacto" class="btn px-4" style="background: var(--incb-azul-oscuro); border-color: var(--incb-azul-oscuro); color:#fff; border-radius:.3rem; font-weight:600;"><i class="bi bi-envelope-fill me-2"></i>Escríbenos para más información</a></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded', function () {
  const links = document.querySelectorAll('.js-especialidad-link');
  const collapse = document.getElementById('navDesktopLinks');
  const offcanvas = document.getElementById('navOffcanvas');
  function activate(hash) { const target = document.querySelector(hash); const tab = document.querySelector('[data-bs-target="' + hash + '"]'); if (!target || !tab || !window.bootstrap) return false; bootstrap.Tab.getOrCreateInstance(tab).show(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); return true; }
  links.forEach(function (link) { link.addEventListener('click', function (event) { const url = new URL(link.href, window.location.href); if (url.pathname !== window.location.pathname || !url.hash) return; event.preventDefault(); history.replaceState(null, '', url.hash); activate(url.hash); if (collapse && collapse.classList.contains('show')) bootstrap.Collapse.getOrCreateInstance(collapse).hide(); if (offcanvas && offcanvas.classList.contains('show')) bootstrap.Offcanvas.getOrCreateInstance(offcanvas).hide(); }); });
  if (window.location.hash.indexOf('#tab-') === 0 && activate(window.location.hash)) history.replaceState(null, '', window.location.hash);
});
</script>
<?php require __DIR__ . '/../includes/footer.php'; ?>
